version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mural_db
      POSTGRES_USER: usuario_mural
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Refleja tus cambios en tiempo real
    env_file:
      - .env    # ¡Lee tu bóveda secreta automáticamente!
    depends_on:
      - db
    environment:
      POSTGRES_DB: mural_db
      POSTGRES_USER: usuario_mural
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      # --- AGREGADO PARA EL PROFE ---
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=adminpassword123
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser --noinput || true &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
