# Generated by Django 6.0.5 on 2026-05-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=250)),
                ('categoria', models.CharField(choices=[('URG', '🔴 Urgente / Peligro'), ('INF', '🟡 Infraestructura / Roturas'), ('OBS', '🔵 Observación / Comentario')], default='OBS', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
