# Generated by Django 6.0.5 on 2026-06-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_nota_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='denuncias_fotos/'),
        ),
    ]
